[package]
name = "RecordAdder"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.26"
egui = "0.26"
arboard = "3"
mlua = { version = "0.9", features = ["luau"] }
tiny_http = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
